version: '3.8'

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Direct access to frontend
    environment:
      - VITE_API_URL=https://localhost/api  # API via nginx HTTP
      - CHOKIDAR_USEPOLLING=false
      - WATCHPACK_POLLING=false
    networks:
      - blog-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx reverse proxy (API only)
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"       # HTTP API access
      - "443:443"     # HTTPS API access
    networks:
      - blog-network
    restart: unless-stopped

networks:
  blog-network:
    driver: bridge