version: '3.8'

services: 
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://udeesha:ObuUxhAzY0qnAAr7Z57pBQ@lucid-grub-16179.j77.aws-ap-south-1.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full
      - JWT_SECRET=SECRET
      - CLOUDINARY_API_KEY=937831317112348
      - CLOUDINARY_API_SECRET=hAk3NQxuG7jL3stvrtE4cbN8JIw
      - CLOUDINARY_CLOUD_NAME=dmeiyssiy
    depends_on:
      db:
        condition: service_healthy
    networks:
      - blog-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VITE_API_URL=${API_URL:-http://localhost:3000}
    depends_on:
      - backend
    networks:
      - blog-network
    restart: unless-stopped
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro

networks:
  blog-network:
    driver: bridge

secrets:
  db_password:
    file: ./secrets/db_password.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt