name: "Docker Security Scan"

on:
  push:
    branches: [ "main", "develop", "Feature/Udeesha" ]
    paths: 
      - 'backend/Dockerfile'
      - 'backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/Dockerfile'
      - 'backend/**'

jobs:
  docker-scan:
    name: Docker Image Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        load: true
        tags: blog-app:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'blog-app:${{ github.sha }}'
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'
        
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'
        
    - name: Run Trivy vulnerability scanner (JSON output)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'blog-app:${{ github.sha }}'
        format: 'json'
        output: 'trivy-results.json'
        
    - name: Upload Trivy JSON results
      uses: actions/upload-artifact@v4
      with:
        name: trivy-scan-results
        path: trivy-results.json
        
    - name: Run Hadolint (Dockerfile linter)
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: ./backend/Dockerfile
        format: sarif
        output-file: hadolint-results.sarif
        no-fail: true
        
    - name: Upload Hadolint results
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: hadolint-results.sarif
        
    - name: Docker Scout CVE scan
      uses: docker/scout-action@v1
      if: always()
      with:
        command: cves
        image: 'blog-app:${{ github.sha }}'
        sarif-file: 'scout-results.sarif'
        summary: true
      continue-on-error: true
        
    - name: Upload Docker Scout results
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'scout-results.sarif'
      continue-on-error: true